### ISSUE TITLE
Research how to publish packages for Android, iOS and Flutter

### ISSUE THREAD

**Issue by arnaubennassar** [iden3/iden3-mobile#16]
The iden3 client library should be distributed in a dev friendly manner for each platform.
Each of this platforms has it's own package system:
- Android: maeven (which can be used in different ways)
- iOS: [cocoapods](https://guides.cocoapods.org/making/making-a-cocoapod.html), [swift package manager](https://github.com/apple/swift-package-manager) 
- Flutter: [pub-dev](https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin)

**Note: Flutter have the concept of package and plugin. Plugin refers to code that runs on the native side (Android/iOS), so that's what we are interested on.**

We should decide what we use to distribute the library in each platform:
- [x] Android: GitHub packages for the gomobile part, Maeven Central for the library wrapping gomobile
- [x] iOS: Coccoapods and SPM
- [x] Flutter: pub-dev

**Comment by arnaubennassar** [comment]
On the Android side: there is three types of Maeven repository:
* Local: aka your computer, not relevant for this
* Central: it's kind of the official thing, and the first thing that will be checked by Maeven when installing a new dependency.
* Remote: other repositories such as github, jitpack or bintray. The downside of this solution is that it requires extra setup to import packages from it. For instance, right now github require to use a token (you must be registered to github to obtain this token).

It may seem obvious to go for the central option, the only bad thing is that the setup process is a bit slow and it may force us to add some metadata that we don't have at the moment such as javadoc.

**Comment by arnaubennassar** [comment]
After some internal discussion we've decided to use GitHub Packages and Maeven Central for Android.

The idea is that the artifacts that gomobile generate and will be used mostly by us will go to GitHub. On the other  hand the Android library that will wrap the gomobile part and is the one that should be used outside of iden3 goes to Maeven Central. That being said, for agility it's likely that we also use GitHub packages for the second wile it's not mature enougth.

**Comment by rauljareno** [comment]
About iOS: Between Cocoapods and Swift package manager. As the framework should be used for integrators, is ok to have the more options as possible. I would suggest to start with Cocoapods as it has bigger adoption over time than SPM and is the most commonly used, just for the case of not having to force some developer to integrate a new package system in their app when most of the third party frameworks that the developer might be using are coming from Cocoapods. The newer the package system, less adoption it will have, even if is better. So I prefer not to choose but I need to choose between one or another, I choose Cocoapods. That's my two cents.

**Comment by arnaubennassar** [comment]
> About iOS: Between Cocoapods and Swift package manager. As the framework should be used by integrators, is ok to have the more options as possible. I would suggest to start with Cocoapods ...

I think it make sense to be as integrator friendly as possible, and so to include releases for both package managers. However, for the framework binded by Gomobile, as it's not addressed to integrators, I think we can go just with cocoapods.

**Comment by rauljareno** [comment]
Both wrapper and gomobile frameworks have to use the same package managers, as the integrator will need to setup both packages, using cocoapods or SPM, even though will be using only the wrapper for integration.

**Comment by arnaubennassar** [comment]
In this case we will distribute both for cocoapods and SPM
