### ISSUE TITLE
Specify API for phase1

### ISSUE THREAD

**Issue by arnaubennassar** [iden3/iden3-mobile#17]
A proposal for an API that fulfills the requirements of [Phase 1](https://github.com/iden3/go-iden3-client/projects/1):

```go

// NewIdentity creates a new identity
// NOTE: New is mapped to new_ since new is a reserved word, so it's better to chose  NewIdentity
// DISCUSSION#1: Simplify input by requiring a path and create kOp, storage and keyStore transparently ?
func (i *Identity) NewIdentity(cfg Config, kOpComp *babyjub.PublicKeyComp, extraGenesisClaims []merkletree.Entrier, storage db.Storage, keyStore *keystore.KeyStore, idenStateReader idenstatereader.IdenStateReader) error {}

// Load loads an already created identity
// involved in DISCUSSION#1
func (i *Identity) Load(storage db.Storage, keyStore *keystore.KeyStore, idenStateReader idenstatereader.IdenStateReader) error {}

// RequestClaim sends a petition to issue a claim to an issuer.
// This function will eventually trigger the registered event "OnIssuerResponse" using the returned string by the function to reference the event
// NOTE: USES Events (because very slow async)
func (i *Identity) RequestClaim(endpoint, data string) string {}

// ProofCredential sends a CredentialValidity build from the given CredentialExistance to a verifier
// the callback is used to check if the verifier has accepted the credential as valid
// NOTE: USES Callback (because fast async)
func (i *Identity) ProofCredential(endpoint string, cred CredentialExistence, c Callback) {}

// RegisterEventHandler stores a Event interface to notify the native host on certain situations
func (i *Identity) RegisterEventHandler(e Event) {}
```

**Note:** Some of the types maybe wrapped in order to be mobile friendly.

This API will implement two types of async patterns:
* Callback: it's more convenient for the library consumers but it's not feasible on certain scenarios (very long time to response, situations that are not triggered by the host)
* Events:A bit harder to handle from the point of view of the consumer, but solve what callbacks can't

**Comment by arnaubennassar** [comment]
About DISCUSSION#1: I will prefer to ask for a path, and store there all the files related to a given identity. This way it would be trivial for the host to implement multi identity:
```
iden3.NewIdentity(".../alias1/", ...)
iden3.Load(".../alias1/", ...) 
iden3.NewIdentity(".../alias2/", ...)
iden3.Load(".../alias2/", ...)
```

A part from that, this approach it's easier to implement both from the point of view of the consumer and from the library itself.

As this is a very early stage and some of the related components will evolve and new ones will appear I prefer this. What do you think @ed255 ?

**Comment by ed255** [comment]
> About DISCUSSION#1: I will prefer to ask for a path, and store there all the files related to a given identity. This way it would be trivial for the host to implement multi identity:
> 
> [...]
> 
> As this is a very early stage and some of the related components will evolve and new ones will appear I prefer this. What do you think @ed255 ?

Sounds good to me for this stage!  This should work for Android.  In the future we need to check if this also works for iOS.

**Comment by arnaubennassar** [comment]
More detailed proposal:

```go
// NewIdentity creates a new identity
func (i *Identity) NewIdentity(pass string, extraGenesisClaims []merkletree.Entrier) error {}

// Load loads an already created identity
func (i *Identity) Load(storePath string) error {}

// RequestClaim sends a petition to issue a claim to an issuer.
// At the moment it's possible to send arbitrary data to the issuer in form of tring.
// This function will eventually trigger the registered event "OnIssuerResponse"
func (i *Identity) RequestClaim(endpoint, data string) string {}

// GetReceivedClaimsCount returns the number of received claims
func (i *Identity) GetReceivedClaimsCount() int {}

// GetReceivedClaim returns the requested received claim
func (i *Identity) GetReceivedClaim(pos int) ([]byte, error) {

// ProofClaim sends a credentialValidity build from the credentialExistance corresponding to the credIndex to a verifier
// the callback is used to check if the verifier has accepted the credential as valid
func (i *Identity) ProofClaim(endpoint string, credIndex int, c Callback) {}

// RegisterEventHandler stores a Event interface to notify the native host on certain situations
func (i *Identity) RegisterEventHandler(e Event) {}
```

So far this proposal exposes received claims instead of credentialExistence. An those claims are exposed just as an array of bytes. I'm not really happy with thisbut it's not clear to me what we should expose.

A part from that, claims must be accessed one by one, according to it's index. This is done this way because gomobile doesn't bind array/slice. That being said, it's easy to add a bit of code on the native side in order to build something nicer (example: ArrayList in Java) .

**Comment by ed255** [comment]
> More detailed proposal:
> 
> ```go
> // NewIdentity creates a new identity
> func (i *Identity) NewIdentity(pass string, storePath string, extraGenesisClaims []merkletree.Entrier) error {}

I guess this would be:
```go
func NewIdentity(pass string, storePath string, extraGenesisClaims []merkletree.Entrier) (*Identity, error) {}
```

> ```go
> // Load loads an already created identity
> func (i *Identity) Load(storePath string) error {}

I guess this would be:
```go
func Load(storePath string) (*Identity, error) {}
```

> ```go
> // RequestClaim sends a petition to issue a claim to an issuer.
> // At the moment it's possible to send arbitrary data to the issuer in form of tring.
> // This function will eventually trigger the registered event "OnIssuerResponse"
> func (i *Identity) RequestClaim(endpoint, data string) string {}

What is the returned string?  Shouldn't this return a ticket or some id of the pending request?  How do you map a given RequestClaim with the credential index later?

> ```go
> // GetReceivedClaimsCount returns the number of received claims
> func (i *Identity) GetReceivedClaimsCount() int {}
> 
> // GetReceivedClaim returns the requested received claim
> func (i *Identity) GetReceivedClaim(pos int) ([]byte, error) {

I did an gomobile-friendly Array implementation for byte slices, you may find it useful:
https://github.com/iden3/go-iden3-client/blob/master/gomobile/httpprovider.go#L99

Unfortunately go doesn't have generics, so it needs a new array structure for each type :(

> // ProofClaim sends a credentialValidity build from the credentialExistance corresponding to the credIndex to a verifier
> // the callback is used to check if the verifier has accepted the credential as valid
> func (i *Identity) ProofClaim(endpoint string, credIndex int, c Callback) {}
> 
> // RegisterEventHandler stores a Event interface to notify the native host on certain situations
> func (i *Identity) RegisterEventHandler(e Event) {}
> ```
> 
> So far this proposal exposes received claims instead of credentialExistence. An those claims are exposed just as an array of bytes. I'm not really happy with thisbut it's not clear to me what we should expose.

> A part from that, claims must be accessed one by one, according to it's index. This is done this way because gomobile doesn't bind array/slice. That being said, it's easy to add a bit of code on the native side in order to build something nicer (example: ArrayList in Java) .

Although claim indexes may seem strange at the beginning, I think it has two advantages:
1. It will be easier to integrate with flutter.
2. It will be a better match to the ClaimDB.

So I think claim indexes are a good solution, and all functions that deal with claims will take as input the index of the claim.  For example one function would take the claim index and return a string representation of the claim, maybe in JSON, so that the consumer can parse it and display it for the user.

**Comment by arnaubennassar** [comment]
Regardless `NewIdentity` and `Load`: Identity is mapped as a class in Java, so things look this way: ```java

// with current propposal:
import iden3mobile.Identity;
Identity myIdentity;
//...
myIdentity = new Identity();
myIdentity.newIdentity(...);
// After this you can access the created identity whith myIdentity.method()

// ---------

// with suggested changes:
import iden3mobile.Identity;
Identity myIdentity;
// ...
myIdentity = new Identity();
myIdentity = myIdentity.newIdentity(...);
// After this you can access the created identity whith myIdentity.method()
```

I'm aware that on the go side it looks a bit weird, but to me it looks nicer on Android (Java). That being said, I've no clue on how it will look like on Kotlin, Objective-C and Swift.

What do you think of it @rauljareno ? Do you have any opinion on this two options, which one is more idiomatic? Can you imagine how it will map on the other languages?

A part from that, I've just realized that this looks ugly:
```java
myIdentity = new Identity();
myIdentity.newIdentity(...);
```
Maybe it's better to rename `newIdentity` to `createIdentity`.

**Comment by rauljareno** [comment]
I have a doubt, why you are creating a method for creating a newIdentity? is not better to create the identity already in the constructor of the Identity object? so you just do myIdentity = new Identity(), and that's it?

**Comment by arnaubennassar** [comment]
@rauljareno You're right! I will add the constructor. That being said, in the case of the load function we've the same problem:
```java
myIdentity = new Identity(...);
// ...

myIdentity = myIdentity.load(...);
// vs
myIdentity.load(...);
```

**Comment by arnaubennassar** [comment]
With the suggested changes, the two function discussed above will look like this:
```go
// NewIdentity creates a new identity
func NewIdentity(storePath, pass string,) (*Identity, error) {}

// NewIdentityLoad loads an already created identity
func NewIdentityLoad(storePath string) (*Identity, error) {}
```

This two functions use a special naming convention to bind as Java classes (New<Struct name>... (...) *<Struct name>) As described [here](https://github.com/golang/mobile/commit/3f7b83ffd484b70ccd24d66425b488dcf680e6da).

This results in the following Java code:
```java
	public Identity(String storePath, String pass) {
		this.refnum = __NewIdentity(storePath, pass);
		Seq.trackGoRef(refnum, this);
	}

	public Identity(String storePath) {
		this.refnum = __NewIdentityLoad(storePath);
		Seq.trackGoRef(refnum, this);
	}
```

Note that I haven't resolved yet how to bind `[]merkletree.Entrier` for the extra genesis claims.

**Comment by arnaubennassar** [comment]
An updated spec accounting all the suggestions:
```go
// NewIdentity creates a new identity
func NewIdentity(storePath, pass string, extraGenesisClaimsBytes *BytesArray) (*Identity, error) {}

// NewIdentityLoad loads an already created identity
func NewIdentityLoad(storePath string) (*Identity, error) {}

// RequestClaim sends a petition to issue a claim to an issuer.
// At the moment it's possible to send arbitrary data to the issuer in form of tring.
// This function will eventually trigger the registered event "OnIssuerResponse"
func (i *Identity) RequestClaim(endpoint, data string) *Ticket {}

// GetReceivedClaimsCount returns the number of received claims
func (i *Identity) GetReceivedClaimsCount() int {}

// GetReceivedClaim returns the requested received claim
func (i *Identity) GetReceivedClaim(pos int) ([]byte, error) {}

// ProofClaim sends a credentialValidity build from the credentialExistance corresponding to the credIndex to a verifier
// the callback is used to check if the verifier has accepted the credential as valid
func (i *Identity) ProofClaim(endpoint string, credIndex int, c Callback) {}

// RegisterEventHandler stores a Event interface to notify the native host on certain situations
func (i *Identity) RegisterEventHandler(e Event) {}

// GetTicketsCount returns tha amount of open tickets of an identity
func (i *Identity) GetTicketsCount() int {}

// GetTicket returns tha requested open ticket of a identity
func (i *Identity) GetTicket(pos int) *Ticket {}
 ```

Since this solves all the pointed concerns I'm closing the issue. Please feel free to reopen it if you have further commentaries.

**Comment by arnaubennassar** [comment]
Updated spec addressing the suggested changes:
```go
type	Identity struct {
	Tickets             *TicketsArray
}

// NewIdentity creates a new identity
// this funciton is mapped as a constructor in Java
func NewIdentity(storePath, pass string, extraGenesisClaims *BytesArray) (*Identity, error) {}

// NewIdentityLoad loads an already created identity
// this funciton is mapped as a constructor in Java
func NewIdentityLoad(storePath string) (*Identity, error) {}

// RequestClaim sends a petition to issue a claim to an issuer.
// This function will eventually trigger the registered event "OnIssuerResponse".
// The reurned string will match the identifier of the event,
//  and potentially the identifier of a ticket that will be added to the identit
func (i *Identity) RequestClaim(endpoint, data string) string {}

// ProofCredential sends a credentialValidity build from the given credentialExistance to a verifier
// the callback is used to check if the verifier has accepted the credential as valid
func (i *Identity) ProofClaim(endpoint string, credIndex int, c Callback) {}

// GetReceivedClaimsLen return the amount of received claims by the identity
func (i *Identity) GetReceivedClaimsLen() int {}

// GetReceivedClaim returns the requested claim
func (i *Identity) GetReceivedClaim(pos int) ([]byte, error) {}

type Event interface {
	OnIssuerResponse(string, string, []byte, error)
}

type Callback interface {
	VerifierResponse(bool, error)
}

type Ticket struct {
	Id          string
	LastChecked int64
	Type        string
}

// RegisterEventHandler stores a Event interface to notify the native host on certain situations
func (i *Identity) RegisterEventHandler(e Event) {}

type BytesArray struct {}
func NewBytesArray() *BytesArray {}
func (ba *BytesArray) Len() int {}
func (ba *BytesArray) Get(i int) []byte {}func (ba *BytesArray) Append(bs []byte) {}

type TicketsArray struct {}
func (ta *TicketsArray) Len() int {}
func (ta *TicketsArray) Get(i int) *Ticket {}
```

**Comment by arnaubennassar** [comment]
Changes done to last proposal:

* The way TicketsArray was implemented could lead to memory problems.This changes using map instead should fix it:
```go
// type TicketsArray struct {}
// func (ta *TicketsArray) Len() int {}
// func (ta *TicketsArray) Get(i int) *Ticket {}

type TicketsMap struct {}
type TicketsMapInterface interface {
	F(*Ticket) error
}
func (tm *TicketsMap) Get(key string) (*Ticket, error) {}
func (tm *TicketsMap) ForEach(handler TicketsMapInterface) error {}
```
Then in Java, to build an array of tickets:
```java
TicketsMap tickets = myIdentity.getTickets();
List<HashMap> ticketList = new ArrayList<HashMap>();
try {
  tickets.forEach(new TicketsMapInterface() {
    @Override
    public void f(Ticket ticket) throws Exception {
      ticketList.add(ticketToMap(ticket));
    }
  });
} catch (Exception e) {
  // ...
}
// have fun with ticketList
```
* The event handler now is registered per identity, therefore the constructor methods now include an Event parameter.
* The method ProofClaim has been renamed to proveClaim.
* The method RequestClaim now returns a *Ticket instead of  a string.

You can have a look at the mock up code that already implements this specification in this [branch]:(https://github.com/iden3/go-iden3-client/tree/mockup)
* [Go code](https://github.com/iden3/go-iden3-client/tree/mockup/go/mobile)
* [Java generated signatures](https://github.com/iden3/go-iden3-client/tree/mockup/go/mobile/iden3mobile)
* [Flutter test app](https://github.com/iden3/go-iden3-client/tree/mockup/flutter)

@rauljareno I'd would be nice if you review the Android / Flutter part of this. Also note that you can find the generate Go code for Android [here](https://github.com/iden3/go-iden3-client/tree/mockup/flutter/android/app/src/main/libs) to use it as it's more convenient for you.

The final API of the library (for this phase) should be quite similar to what is shown on the branch, unless there is further feedback. So @arnaucube and @ed255 have a look to it too!

**Comment by ed255** [comment]
The `ForEach` + `Get` by key api for accessing lists of things looks good to me!  It's a nice way to allow concurrent access with just a few methods.  I would consider extending this API to the `ReceivedClaims` list.

> Updated spec addressing the suggested changes:
> 
> ```go
> type	Identity struct {
> 	Tickets             *TicketsArray
> }
> 
> // NewIdentity creates a new identity
> // this funciton is mapped as a constructor in Java
> func NewIdentity(storePath, pass string, extraGenesisClaims *BytesArray) (*Identity, error) {}
> 
> // NewIdentityLoad loads an already created identity
> // this funciton is mapped as a constructor in Java
> func NewIdentityLoad(storePath string) (*Identity, error) {}

Doesn't the load method also need a password?

Also, I was thinking that from the java part it's not obvious that one constructor is creating a new identity while the other is creating a new object by loading a previously created identity.  We can leave it like this for this phase, but here's an idea:
```go
type NewIdentityConfig struct {
  extraGenesisClaims *BytesArray
}

type LoadIdentityConfig struct {}

> // NewIdentity creates a new identity
> // this funciton is mapped as a constructor in Java
> func NewIdentity(cfg NewIdentityConfig, storePath, pass string) (*Identity, error) {}
> 
> // NewIdentityLoad loads an already created identity
> // this funciton is mapped as a constructor in Java
> func NewIdentityLoad(cfg LoadIdentityConfig, storePath, pass string) (*Identity, error) {}
```

This way in java it would look explicit if it's a "new" or a "load" with the class `NewIdentityConfig` or `LoadIdentityConfig` as first argument to the constructor.

**Comment by arnaubennassar** [comment]
Since all the suggestions have been addressed I'm closing this issue. Feel free to reopen it if you have further comments.
