### ISSUE TITLE
Difficulties using DB keys converted to strings

### ISSUE THREAD

**Issue by arnaubennassar** [iden3/iden3-mobile#58]
When receiveing a "RequestClaim" event, the data JSON includes a DB key converted to string.
It's hard to convert the string back to bytes matching the Go marshal/unmarshal format.This is needed to call methods that require the db key as parameter.

**Comment by arnaubennassar** [comment]
Potential solutions:
* Create an additional method in Go that uses string instead of []byte as input
* Use typed events (each type of event uses it's own handler with specific parameters)
* Implement encoders on each target platform (Flutter, Android, iOS)

**Comment by ed255** [comment]
It seems that go's json.Marshal encodes `[]byte` as a base64 string by default. To avoid having to do conversions, I think we can replace the usage of claimDB keys by strings (since we are building the key the way we want).
