### ISSUE TITLE
Build and publish Android binaries in a CI fashion

### ISSUE THREAD

**Issue by arnaubennassar** [iden3/iden3-mobile#69]
The idea is that the `.aar` (and in the future what iOS needs) gets published automatically.
We've yet to decide when this process gets triggered, it could be on every PR to master or only when some specific tags are used (such as version or compatibility layer tags).

Ideally the solution used would provide a os x environment to support the upcoming iOS builds.

**Comment by ed255** [comment]
Via #76 I have added a github action that builds the aar every time a commit is pushed to master.  The aar is published in a new beta release each time.

An future improvement to this workflow will be to send notifications if the build fails / succeeds via keybase: #77
